### ISSUE TITLE
Automated Changelogs

### ISSUE THREAD

**Issue by ayuhito** [DecliningLotus/fontsource#434]
# Repo Management
This repository lacks an automated changelog system since it doesn't follow a perfect rendition of Semver as shown in our existing [`CHANGELOG.md`](https://github.com/fontsource/fontsource/blob/main/CHANGELOG.md ). I think it'd be worth it for us to setup a comprehensive changelog system especially as our monorepo grows with more sub-projects, such as the API or website or upcoming plugins. It would be great to have individual changelogs for them as well which can be differentiated by adding a scope to the PR commit message e.g. `feat(website): message` or `fix(api): message`. Commit messages without a scope would refer to the repository as a whole or scripts.

Perhaps we can finally add a new changelog to track when a package updates from Google instead of a change from Fontsource too.

## Implementation
Due to the non-perfect rendition of Semver, we can't just drop in [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog). We'll need to make a custom adapter to match the template we have. I do like Gatsby's style of things and this might be a useful reference - https://github.com/gatsbyjs/gatsby/tree/master/scripts/gatsby-changelog-generator.

Another thing to consider is that except for font packages, nothing is ever "published" for the scripts or website etc. We can't rely on publish lifecycles like Gatsby or other repos to automatically update the changelog. It might need to be webhook or Actions based after a PR is merged. 

We don't need to enforce the conventional-commit format for all commits. Just the final PR commit message that is squashed. I'm thinking [semantic-pull-requests](https://github.com/zeke/semantic-pull-requests) appropriately handles that.

**Comment by akphi** [comment]
Have you checked out https://github.com/changesets/changesets ? We use it for our `monorepo` and it allows having separate changelog for each package.

**Comment by ayuhito** [comment]
I actually have looked at Changesets before, but their process is pretty incompatible with our setup. 

Our entire versioning strategy would go against their Semver fundamentals. It's necessary for us to write something custom extending conventional-changelog to accommodate that.

**Comment by ayuhito** [comment]
The Next.js release process might be better to take inspiration from: https://github.com/vercel/next.js/blob/canary/release.js

**Comment by airtonix** [comment]
> I actually have looked at Changesets before, but their process is pretty incompatible with our setup.
> 
> Our entire versioning strategy would go against their Semver fundamentals. It's necessary for us to write something custom extending conventional-changelog to accommodate that.

You shoud first document what this `Our entire versioning strategy` is. 

I have implemented several different kinds of changelog automation for various groups, all without requiring to actually publish anything... merely merge your working PRs.

So understanding what your current process is and why you do it would help everyone understand : 

- is it the best solution? 
- could it change slightly and adopt a drop in tool?  
- is it in fact: not at all incompatiable with current drop in tools?

**Comment by ayuhito** [comment]
> You shoud first document what this Our entire versioning strategy is.

It is documented at the top of [`CHANGELOG.md`](https://github.com/fontsource/fontsource/blob/main/CHANGELOG.md). As mentioned in this issue, it's close to Semver, but not exact.

**Comment by airtonix** [comment]
> > You shoud first document what this Our entire versioning strategy is.
> 
> It is documented at the top of [`CHANGELOG.md`](https://github.com/fontsource/fontsource/blob/main/CHANGELOG.md). As mentioned in this issue, it's close to Semver, but not exact.

ok so maybe it's too late in the night and I'm too tired but what do you mean by "it's close to Semver, but not exact"? 

a) that unlike semver a patch in the fontsource repo is not always backwards compatiable?  
b) something else? 

because if it's `a`. Then it doesn't matter. 


---


More observations:

- I see that the workflows setup as a [cronjob](https://github.com/fontsource/fontsource/blob/main/.github/workflows/cron-run.yml#L54-L73)
- and then we npm [publish straight away](https://github.com/fontsource/fontsource/blob/main/.github/workflows/cron-run.yml#L80-L85)

I would instead: 

- stop using `mass-publish`, (changesets replaces this)
- don't publish when `main` changes.
- write a tool that creates a `.changeset/.*.md` based on what packages changed from your cron job. it should look like 🅰️ 👇🏻 
- let the cronjob workflow commit the generated changesets to `main` 
- install the [changesets bot and action](https://github.com/changesets/action) so it handles creating the release PR for you and contiually rolls up new changes into that PR
- now, to release to npm, and generate changelogs you merge the release PR

🅰️
```md
---
'@fontsource/...': patch
'@fontsource/...': patch
'@fontsource/...': patch
'@fontsource/...': patch
---

Auto generated google font change, you could also put other interesting information here
```

**Comment by ayuhito** [comment]
Here's my main concern and why I wrote a custom publisher. Does it scale well? If Fontsource pushes a minor release, we end up publishing over 1500+ NPM packages in a single CI run. V5 gets closer to 2000 as we're splitting variable fonts into separate packages.

We used to use Lerna in the past and that often failed regularly due to its architecture. The custom publisher amends those limitations and has extra functionality to recover from half-done publishes (e.g. 700 packages are published before it encountered an API error leaving the rest unpublished with no way to publish the other 700).

Monorepo tools like Changesets aren't necessarily designed for that sort of scale and it's quite frankly unrealistic to expect them to support such usecases. I don't particularly think it's sound to create and delete so many Changeset files into the repository either.

I've already built a POC in a branch using a similar method to the Next.js repo which seemed very viable and a lot more simpler to implement. Just never got around finishing that as I've been focusing on other things.

**Comment by ayuhito** [comment]
> because if it's a. Then it doesn't matter.

Now that I've reviewed it again, yeah the versioning strategy doesn't matter. It would work fine in that regard. Awesome project, but it still doesn't seem like a good fit for Fontsource overall.

**Comment by airtonix** [comment]
> If Fontsource pushes a minor release, we end up publishing over 1500+ NPM packages in a single CI run. V5 gets closer to 2000 as we're splitting variable fonts into separate packages.

Not if you use independant versioning (the default with changesets).

But i suppose you knew that, which means you want everything deployed again when one package changes?

**Comment by ayuhito** [comment]
> But i suppose you knew that, which means you want everything deployed again when one package changes?

Patch releases will affect individual packages - that's not an issue.

Minor and major releases affect all packages. They all need to be updated to the same version then.

**Comment by ayuhito** [comment]
Now that we switched over to a completely different monorepo setup for V5, Changesets became feasible to run over the small number of utility packages we have here and I think the automatic changelog generation for those packages is sufficient.

I still think we should still implement a custom changelog generator for [font-files](https://github.com/fontsource/font-files), but I'll create a separate issue for that as the scope has changed from the original intentions of this PR.
